x-logging: &logging-systemd
  logging:
    driver: journald

x-logging-loki: &logging-loki
  logging:
    driver: loki
    options:
      mode: "non-blocking"
      loki-url: http://127.0.0.1:3100/loki/api/v1/push
      max-size: "50m"
      max-file: "2"

x-build: &build
  image: "neko"
  build:
    context: .
    dockerfile: ./Dockerfile
    tags:
      - neko-alpine:latest

x-healthcheck-neko: &healthcheck-neko
  healthcheck:
    test: ["CMD", "neko-healthcheck"]
    interval: 10s
    timeout: 5s
    retries: 8

services:
  neko:
    <<:
      #- *logging-systemd
      #- *logging-loki
      - *build
      - *healthcheck-neko
    container_name: neko
    restart: always
    hostname: neko
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_NAT1TO1: 127.0.0.1
