x-logging: &logging-systemd
  logging:
    driver: journald

x-logging-loki: &logging-loki
  logging:
    driver: loki
    options:
      mode: "non-blocking"
      loki-url: http://127.0.0.1:3100/loki/api/v1/push
      max-size: "50m"
      max-file: "2"

x-build: &build
  image: "neko"
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  neko:
    <<:
      #- *logging-systemd
      #- *logging-loki
      - *build
    container_name: neko
    hostname: neko
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_DEBUG: 1
      NEKO_MEMBER_PROVIDER: multiuser
      NEKO_SESSION_COOKIE_SECURE: 0
      NEKO_WEBRTC_ICELITE: 0
      NEKO_WEBRTC_LEGACY: 0
      NEKO_SERVER_PROXY: 0
      NEKO_SERVER_BIND: 0.0.0.0:8080
      NEKO_SERVER_PUBLIC_ADDRESS: http://localhost:8080
      NEKO_WEBRTC_CANDIDATE_TYPES: host
      NEKO_WEBRTC_ICESERVERS_FRONTEND: "[]"
      NEKO_WEBRTC_ICESERVERS_BACKEND: "[]"
